site_name: yangxuebin
site_description: 杨学彬的个人网站
site_author: 杨学彬

theme:
  name: gitbook
  custom_dir: overrides/  # Directory for custom theme files
  logo: ./img/headshot.jpg  # Optional: Adds headshot to header if desired


nav:
  - Home: index.md
  - About Me: about_me.md
  - My Posts: my_posts.md
  - Life Recording: record_life.md

plugins:
  - search  # Enables search functionality

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false  # 使用 Highlight.js
      linenums: true  # 显示行号
      anchor_linenums: true  # 行号锚点
  - pymdownx.arithmatex:  # 添加此扩展
      generic: true  # 兼容 MathJax 和 KaTeX
      

extra_css:
  - stylesheets/extra.css  # Custom styles for sidebar
  - stylesheets/index.css
  - stylesheets/about_me.css
  - stylesheets/my_posts.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/monokai.min.css
  - stylesheets/recode_life.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - javascripts/highlight_init.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/python.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/cpp.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/javascript.min.js
  - javascripts/mathjax_config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/my_posts.js
  - javascripts/recode_life.js


extra:
  static_files:
    - img/headshot.jpg

use_directory_urls: false

not_found_page: 404.html
